# 01 - Data Collection

## Diamond Price Prediction

### Objective

This notebook performs:

- Dataset loading
- Initial inspection
- Data type checking
- Missing value checking
- Duplicate checking
- Save raw dataset structure

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
# sau nay dung may khac project van chay duoc

In [2]:
PROJECT_ROOT = Path.cwd().parent

DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

print(PROJECT_ROOT)
print(RAW_DIR)

d:\project\data-science-portforlio\diamond-price-prediction
d:\project\data-science-portforlio\diamond-price-prediction\data\raw

In [3]:
df = pd.read_csv(RAW_DIR/ "train.csv", index_col=0)

In [4]:
df.head()

    carat        cut color clarity  depth  table     x     y     z  price
id
0    1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1    2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2    0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3    0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4    1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [5]:
##Dataset Shape

rows, cols = df.shape

print(rows)
print(cols)

193573
10

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 193573 entries, 0 to 193572
Data columns (total 10 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   carat    193573 non-null  float64
 1   cut      193573 non-null  str
 2   color    193573 non-null  str
 3   clarity  193573 non-null  str
 4   depth    193573 non-null  float64
 5   table    193573 non-null  float64
 6   x        193573 non-null  float64
 7   y        193573 non-null  float64
 8   z        193573 non-null  float64
 9   price    193573 non-null  int64
dtypes: float64(6), int64(1), str(3)
memory usage: 16.7 MB

In [7]:
df.describe()

,carat,depth,table,x,y,z,price
count,193573.000000,193573.000000,193573.000000,193573.000000,193573.000000,193573.000000,193573.000000
mean,0.790688,61.820574,57.227675,5.715312,5.720094,3.534246,3969.155414
std,0.462688,1.081704,1.918844,1.109422,1.102333,0.688922,4034.374138
min,0.200000,52.100000,49.000000,0.000000,0.000000,0.000000,326.000000
25%,0.400000,61.300000,56.000000,4.700000,4.710000,2.900000,951.000000
50%,0.700000,61.900000,57.000000,5.700000,5.720000,3.530000,2401.000000
75%,1.030000,62.400000,58.000000,6.510000,6.510000,4.030000,5408.000000
max,3.500000,71.600000,79.000000,9.650000,10.010000,31.300000,18818.000000

In [8]:
missing = df.isnull().sum()

missing

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
x          0
y          0
z          0
price      0
dtype: int64

In [9]:
duplicates = df.duplicated().sum()

print(duplicates)

0

In [10]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'x', 'y', 'z',
       'price'],
      dtype='str')

In [11]:
numerical_features = df.select_dtypes(include=["number"]).columns.tolist()
categorical_features = df.select_dtypes(include=["object"]).columns.tolist()

print(numerical_features)

print()

print(categorical_features)

['carat', 'depth', 'table', 'x', 'y', 'z', 'price']

['cut', 'color', 'clarity']

C:\Users\nghah\AppData\Local\Temp\ipykernel_18312\2791722327.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = df.select_dtypes(include=["object"]).columns.tolist()

In [12]:
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
df.to_csv(PROCESSED_DIR / "train_collection.csv", index=True)

# summary

## findings

- dataset loaded success
- no preprocessing 
- dataset structure identified
- numerical and categorical 
- missing values inspected
- duplicate rows inspected